# Generated by Django 5.0 on 2024-10-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='intermission',
            field=models.CharField(default='link goes here', max_length=256),
        ),
        migrations.AddField(
            model_name='customuser',
            name='room_id',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
