# Generated by Django 5.0 on 2024-10-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singerqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('social_types', models.CharField(choices=[('tiktok', 'TikTok'), ('X', 'X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('phone_number', 'Phone Number'), ('email', 'Email'), ('n/a', 'N/A')], default='n/a', max_length=12)),
                ('social_contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
