# Generated by Django 5.0 on 2024-10-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singerqueue', '0004_alter_contactinfo_social_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='social_types',
            field=models.CharField(blank=True, choices=[('', 'Please pick a social contact type'), ('tiktok', 'TikTok'), ('X', 'X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('phone_number', 'Phone Number'), ('email', 'Email'), ('n/a', 'N/A')], default='', max_length=12),
        ),
    ]
