# Generated by Django 5.0 on 2024-10-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singerqueue', '0005_alter_contactinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='social_types',
            field=models.CharField(choices=[('', 'Please pick a social contact type'), ('tiktok', 'TikTok'), ('X', 'X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('phone_number', 'Phone Number'), ('email', 'Email')], default='', max_length=12),
        ),
    ]
