# Generated by Django 5.0 on 2024-11-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singerqueue', '0006_alter_contactinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='song_link',
            field=models.URLField(blank=True),
        ),
    ]
